#!/bin/bash

rm -rf /var/log/acme/[[artifactId]]/[[artifactId]]-stdout.log
rm -rf /var/log/acme/[[artifactId]]/[[artifactId]]-stderr.log

##
# http://stackoverflow.com/a/7335524
##

if type -p java; then
    echo found java executable in PATH
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    echo found java executable in JAVA_HOME
    _java="$JAVA_HOME/bin/java"
else
    echo "no java"
    exit 1 # terminate and indicate error
fi

if [[ "$_java" ]]; then

    version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    vendor="$(echo "$(java -XshowSettings:properties -version 2>&1)" | grep "java.vendor = " | awk '{ print $3; }')"

    echo java version: "$version", vendor: "$vendor"

    if [[ "$version" > "1.8" ]] && [[ $vendor == *"Oracle"* ]]; then
        echo version is more than 1.8 and vendor is Oracle
    else
        echo version is less than 1.8 or vendor is not Oracle, please configure Oracle JDK 1.8
        echo Option 1: by setting JAVA_HOME variable to existing setup
        echo Option 2: by installing java from existing repo: https://help.ubuntu.com/community/Java
        exit 1 # terminate and indicate error
    fi
fi

echo "﻿$(readlink -f $(which java))" > ./.java_path.txt

###
# http://askubuntu.com/questions/101962/script-to-only-execute-during-first-install-of-a-package
###

if [ -z "$2" ]; then
  echo "Preinst: clean installation, no actions"
else

  ###
  # http://bash.cyberciti.biz/guide/The_case_statement
  ###

  echo "Preinst: attempting to stop [[artifactId]] service..."

  statusCMD=$(supervisorctl status [[artifactId]])
  stopCMD=$(supervisorctl stop [[artifactId]])

    case "$statusCMD" in
      *RUNNING*)
          echo "Prerm: Attempt to stop service [[artifactId]]: $stopCMD"
        ;;
      *)
          echo "Prerm: Service [[artifactId]] is not running. Status: $statusCMD"
    esac
fi
